runtime: python
env: flex
entrypoint: gunicorn -b :$PORT project_name.wsgi
service: default

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /report/weekly
  script: main.app
